[package]
name = "mechanics"
version = "0.1.0"
edition = "2021"

[dependencies]
gmt_dos-clients = { workspace = true, features = ["nalgebra"] }
anyhow.workspace = true
env_logger.workspace = true
gmt-fem.workspace = true
gmt_dos-actors.workspace = true
gmt_dos-clients_arrow.workspace = true
gmt_dos-clients_fem.workspace = true
gmt_dos-clients_io.workspace = true
gmt_dos-clients_m1-ctrl.workspace = true
gmt_dos-clients_mount = { workspace = true, default-features = false, features = [
    "s8000d002ze30",
] }
gmt_dos-clients_scope = { workspace = true, features = ["server"] }
gmt_dos-clients_scope-client.workspace = true
interface.workspace = true
matio-rs = { workspace = true, features = ["nalgebra"] }
nalgebra = { workspace = true, features = ["serde-serialize"] }
nanorand.workspace = true
tokio.workspace = true
gmt_dos-clients_m2-ctrl.workspace = true
gmt_dos-clients_lom.workspace = true
gmt_dos-clients_windloads.workspace = true

[features]
wfe-rms_scope = []
dp21-rss_scope = []
mount_scope = []
segment-tip-tilt_scope = []
