[workspace]
members = [
  "clients/scope/client",
  "actors/dsl/examples/demo",
  "actors/dsl/examples/scope",
  "actors/dsl/examples/scopes",
  "clients/crseo/tms",
  "clients/lom",
  "book",
  "clients/fem/mech",
  "clients/fem/fem-cuda-solver",
  "clients/servos/edge-sensors",
  "clients/servos/edge-sensors/scopes",
  "clients/servos/edge-sensors/io",
  "demos",
  "clients/dcs",
  "clients/dcs/servos-scopes",
  "systems/agws",
  "systems/m1/modes",
  "clients/scope/hub",
  "clients/optics-state",
]
resolver = "2"

[workspace.package]
authors = ["Rod Conan <rconan@gmto.org>"]
edition = "2024"
license = "MIT"
repository = "https://github.com/rconan/dos-actors"
categories = ["science", "simulation"]
keywords = ["telescope", "astronomy"]

[workspace.dependencies]
gmt_dos-actors = { version = "12.1", path = "actors/" }
gmt_dos-clients = { version = "5.1", path = "clients/core" }
interface = { version = "1.5", path = "interface", package = "gmt_dos-actors-clients_interface" }
gmt-fem = { version = "5.2", path = "clients/fem/model" }
gmt-fem-code-builder = { version = "2.3", path = "clients/fem/builder" }
dos-uid-derive = { version = "5.0", path = "interface/uid-derive/" }
gmt_dos-clients_io = { version = "4.3", path = "clients/io" }
gmt_dos-clients_fem = { version = "5.3", path = "clients/fem/" }
gmt_dos-clients_mount = { version = "4.1", path = "clients/mount/" }
gmt_dos-clients_m1-ctrl = { version = "6.0", path = "clients/m1-ctrl/" }
gmt_dos-systems_m1 = { version = "1.0", path = "systems/m1/" }
gmt_dos-clients_m2-ctrl = { version = "4.0", path = "clients/m2-ctrl/" }
gmt_dos-systems_m2 = { version = "0.1", path = "systems/m2/" }
gmt_dos-clients_servos = { version = "3.1", default-features = false, path = "clients/servos/" }
gmt_dos-clients_arrow = { version = "2.3", path = "clients/arrow/" }
gmt_dos-clients_domeseeing = { version = "4.0", path = "clients/domeseeing/" }
gmt_dos-clients_windloads = { version = "3.0", path = "clients/windloads/" }
gmt_dos-clients_lom = { version = "1.2", path = "clients/lom/" }
gmt_dos-clients_crseo = { version = "5.0", path = "clients/crseo/" }
gmt_dos-clients_transceiver = { version = "2.0", path = "clients/transceiver" }
gmt_dos-clients_scope = { version = "3.1", path = "clients/scope" }
gmt_dos-clients_scope-client = { version = "0.2.2", path = "clients/scope/client" }
gmt_dos-clients_optics-state = { version = "0.1", path = "clients/optics-state" }
log = "0.4.29"
thiserror = "2.0"
tokio-test = "0.4"
nalgebra = "0.34"
tokio = { version = "1.52.1" }
anyhow = "1.0.102"
crseo = { version = "2.5" }
rayon = "1.12.0"
env_logger = "0.11.10"
matio-rs = "1.6"
skyangle = "0.4.0"
nanorand = "0.8.0"
serde = { version = "1.0.228", features = ["derive", "rc"] }
bincode = "2.0.1"
apache-arrow = { version = "58.1", package = "arrow" }
parquet = "58.1"
zip = "8.5.1"
bytes = "1.11.1"
indicatif = { version = "0.18.4" }
tracing = "0.1.44"
flume = "0.12.0"
syn = "2.0"
quote = "1.0"
proc-macro2 = "1.0"
faer-ext = { version = "0.7.1", features = ["nalgebra"] }
faer = "0.23.2"

[profile.release]
lto = "thin"
