[workspace]
members = [
    "actors",
    "actors/uid-derive",
    "clients/windloads",
    "clients/crseo",
    "clients/domeseeing",
    "clients/arrow",
    "clients/mount",
    "clients/io",
    "clients/m1-ctrl",
    "clients/m2-ctrl",
    "clients/fem",
    "clients/crseo/tms",
    "book",
    "grsim/ngao",
    "grsim/ngao-opm",
    "grsim/asms",
    "grsim/open-loop",
    "grsim/active-optics",
]

[workspace.package]
authors = ["Rod Conan <rconan@gmto.org>"]
edition = "2021"
license = "MIT"
repository = "https://github.com/rconan/dos-actors"
categories = ["science", "simulation"]
keywords = ["telescope", "astronomy"]

[workspace.dependencies]
gmt_dos-clients = { version = "2.0.0", path = "clients/", default-features = false }
gmt-fem = { version = "2.0.2" }
gmt_dos-actors = { version = "7.0.0", path = "actors/" }
dos-uid-derive = { version = "2.0.0", path = "actors/uid-derive/" }
gmt_dos-clients_io = { version = "2.0.0", path = "clients/io" }
gmt_dos-clients_fem = { version = "1.0.0", path = "clients/fem/" }
gmt_dos-clients_mount = { version = "1.0.0", path = "clients/mount/" }
gmt_dos-clients_m1-ctrl = { version = "1.0.0", path = "clients/m1-ctrl/" }
gmt_dos-clients_m2-ctrl = { version = "1.0.0", path = "clients/m2-ctrl/" }
gmt_dos-clients_arrow = { version = "1.0.0", path = "clients/arrow/" }
gmt_dos-clients_domeseeing = { version = "1.0.0", path = "clients/domeseeing/" }
gmt_dos-clients_crseo = { version = "1.0.0", path = "clients/crseo/" }
log = "0.4.17"
thiserror = "1.0.36"
tokio-test = "0.4.2"
nalgebra = "0.32.1"
tokio = { version = "1.25.0" }
anyhow = "1.0.68"
crseo = { version = "0.5.0" }
rayon = "1.6.1"
env_logger = "0.10.0"
matio-rs = "1.3.1"
skyangle = "0.2.2"
nanorand = "0.7.0"
serde = { version = "1.0.160", features = ["derive", "rc"] }
