[package]
name = "edge-sensors_scopes"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow.workspace = true
io = { version = "0.1.0", path = "../io" }
gmt_dos-clients_io.workspace = true
gmt_dos-clients_scope-client.workspace = true
interface.workspace = true
tokio = { workspace = true, features = ["rt-multi-thread"] }
