[package]
name = "gmt_dos-clients_scope-macros"
version = "0.4.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
description = "GMT DOS Scope Macros"
documentation = "https://docs.rs/gmt_dos-clients_scope-macros"
readme = "../README.md"
repository.workspace = true
categories.workspace = true
keywords.workspace = true

[dependencies]
proc-macro2 = "1.0.66"
quote = "1.0.32"
serde.workspace = true
syn = "2.0.28"

[lib]
proc-macro = true
