[package]
name = "gmt_dos-clients_transceiver"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow.workspace = true
async-trait = "0.1.72"
bincode = { workspace = true, features = ["serde"] }
directories-next = "2.0.0"
flume = "0.10.14"
gmt_dos-clients = { workspace = true, features = ["clients", "serde"] }
quinn = "0.10.1"
rcgen = "0.11.1"
rustls = { version = "0.21.5" }
serde.workspace = true
thiserror.workspace = true
tokio = { workspace = true, features = ["full"] }
tracing = { version = "0.1.37", features = ["log"] }
tracing-subscriber = { version = "0.3.17", features = ["env-filter"] }

[dev-dependencies]
anyhow.workspace = true
env_logger.workspace = true
gmt_dos-actors.workspace = true
