[package]
name = "scopes"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow.workspace = true
gmt_dos-actors.workspace = true
gmt_dos-clients.workspace = true
interface.workspace = true
gmt_dos-clients_arrow.workspace = true
gmt_dos-clients_io.workspace = true
gmt_dos-clients_scope = { workspace = true, features = ["server"] }
gmt_dos-clients_scope-client.workspace = true
gmt_dos-clients_windloads.workspace = true
tokio = { workspace = true, features = ["rt-multi-thread", "macros"] }

[features]
default = ["gmt_dos-clients_scope/server"]
scope-client = ["gmt_dos-clients_scope/client"]
