[package]
name = "gmt_dos-clients_scopehub"
version = "0.1.0"
edition = "2024"

[dependencies]
syn = { version = "2.0", features = ["full"] }
quote = "1.0"

[lib]
proc-macro = true

[dev-dependencies]
gmt_dos-clients_io.workspace = true
gmt_dos-clients_scope = { workspace = true, features = ["server"] }
interface.workspace = true
