[package]
name = "gmt_dos-clients_scope"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow.workspace = true
async-trait = "0.1.72"
eframe = "0.22.0"
flume = "0.10.14"
gmt_dos-actors.workspace = true
gmt_dos-clients = { workspace = true, features = ["noise"] }
gmt_dos-clients_transceiver = { version = "0.1.0", path = "../transceiver" }
rand_distr = "0.4.3"
serde.workspace = true
thiserror.workspace = true
tokio = { workspace = true, features = ["full"] }
tracing = "0.1.37"

[dev-dependencies]
tracing-subscriber = { version = "0.3.17", features = ["env-filter"] }
