[package]
name = "gmt_dos-clients_scope-client"
version = "0.2.1"
authors.workspace = true
edition.workspace = true
license.workspace = true
description = "GMT DOS Scope Client"
documentation = "https://docs.rs/gmt_dos-clients_scope-client"
readme = "README.md"
repository.workspace = true
categories.workspace = true
keywords.workspace = true

[dependencies]
gmt_dos-clients_scope = { workspace = true, features = ["client"] }

[features]
compress = ["gmt_dos-clients_scope/compress"]
