[package]
name = "tms"
version = "0.1.0"
edition = "2021"

[dependencies]
gmt_dos-actors.workspace = true
gmt_dos-clients = { workspace = true, features = ["noise"] }
gmt_dos-clients_io.workspace = true
gmt_dos-clients_arrow.workspace = true
gmt_dos-clients_crseo.workspace = true
tokio = { workspace = true, features = ["full"] }
anyhow.workspace = true
crseo.workspace = true
toml = "1.1.2"
rand = "0.10.1"
rand_distr = "0.6.0"
polars = { version = "0.53.0", features = ["parquet", "lazy"] }
skyangle = "0.4.0"
