[package]
name = "gmt_dos-clients_domeseeing"
version = "3.0.1"
authors.workspace = true
edition.workspace = true
license.workspace = true
description = "GMT DOS Domeseeing Client"
documentation = "https://docs.rs/gmt_dos-clients_domeseeing"
readme = "README.md"
repository.workspace = true
categories.workspace = true
keywords.workspace = true

[dependencies]
interface.workspace = true
glob = "0.3.0"
bincode = { version = "1.3.3", optional = true }
log.workspace = true
serde = { version = "1.0.145", features = ["derive"] }
thiserror.workspace = true
gmt_dos-clients_io.workspace = true
npyz = { version = "0.8.4", features = ["npz"], optional = true }

[features]
default = ["bincode"]
