[package]
name = "scope"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow.workspace = true
feature = "0.5.1"
features = "0.10.0"
gmt_dos-actors.workspace = true
gmt_dos-clients.workspace = true
interface.workspace = true
gmt_dos-clients_arrow.workspace = true
gmt_dos-clients_io.workspace = true
gmt_dos-clients_scope = { workspace = true }
gmt_dos-clients_windloads.workspace = true
server = "0.1.0"
tokio = { workspace = true, features = ["rt-multi-thread", "macros"] }

[features]
default = ["gmt_dos-clients_scope/server"]
scope-client = ["gmt_dos-clients_scope/client"]
